const testimonials = [
  {
    src: '/src/assets/content/profile.avif',
    user: 'adam123',
    time: '10/06/2024',
    titre: 'Efficacité et disponibilité',
    stars: '4',
    avis: "La réservation de notre hôtel et de nos vols avec alpha oasis s'est faite sans effort. Ils ont trouvé les meilleures offres et leur service était impeccable. Savoir que alpha oasis s'occupe de toute la logistique nous a apporté une tranquillité d'esprit, rendant notre expérience de voyage fluide et sans stress. Nous ferons certainement appel à leurs services pour nos futurs voyages.",
  },
  {
    src: '/src/assets/content/profile.avif',
    user: 'sarah_w',
    time: '15/05/2024',
    titre: 'Service exceptionnel',
    stars: '5',
    avis: 'Alpha Oasis a surpassé nos attentes à chaque étape. Leur équipe est attentive, rapide et professionnelle. Nous avons particulièrement apprécié leur flexibilité et leur souci du détail.',
  },
  {
    src: '/src/assets/content/profile.avif',
    user: 'mohamed_b',
    time: '22/04/2024',
    titre: 'Très satisfait',
    stars: '4',
    avis: 'La plateforme est intuitive et facile à utiliser. Les offres proposées étaient compétitives et la communication claire. Je recommande vivement Alpha Oasis pour tous vos projets de voyage.',
  },
  {
    src: '/src/assets/content/profile.avif',
    user: 'leila_t',
    time: '05/03/2024',
    titre: 'Expérience agréable',
    stars: '5',
    avis: "Une équipe dédiée et réactive qui a pris soin de chaque détail. Notre voyage s'est déroulé sans aucun souci grâce à Alpha Oasis. Merci pour votre professionnalisme !",
  },
  {
    src: '/src/assets/content/profile.avif',
    user: 'youssef_r',
    time: '12/02/2024',
    titre: 'Bonne organisation',
    stars: '4',
    avis: 'Alpha Oasis a su organiser un voyage parfaitement adapté à nos besoins. La réservation a été rapide et efficace, ce qui nous a beaucoup soulagés.',
  },
];

const destination = [
  {
    title: 'Tour gastronomique',
    description: 'Savourez les meilleures spécialités marocaines.',
    country: 'Maroc',
    location: 'Fès',
    duration: 3,
    price: 2800,
    herbergement: true,
    wifi: true,
    petit_dej: false,
    Transfert: false,
    nb_personnes: 20,
    src: 'https://images.unsplash.com/photo-1661081988119-58e40ee39201?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Aventure en forêt',
    description:
      'Balades et découvertes dans les forêts luxuriantes du d`ifran.',
    country: 'Maroc',
    location: 'Ifran',
    duration: 5,
    price: 3900,
    src: 'https://images.unsplash.com/photo-1611358382200-5baf13de1b40?q=80&w=1633&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Séjour dans un riad',
    description:
      'Vivez l’expérience authentique d’un hébergement traditionnel.',
    country: 'Maroc',
    location: 'Médina de Fès',
    duration: 3,
    price: 2500,
    src: 'https://images.unsplash.com/photo-1671181087708-be3050f1974e?q=80&w=740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Sports nautiques',
    description: 'Plongée, kitesurf et paddle dans les eaux de Tamraght.',
    country: 'Maroc',
    location: 'Tamraght',
    duration: 5,
    price: 3700,
    src: 'https://images.unsplash.com/photo-1537174621888-eba6137cf6c9?q=80&w=2080&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Séjour bien-être',
    description: 'Spa, hammams et relaxation dans un cadre authentique.',
    country: 'Maroc',
    location: 'Agadir',
    duration: 5,
    price: 4200,
    src: 'https://images.unsplash.com/photo-1600289730889-17f9ad4c38f0?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Excursion à Chefchaouen',
    description: 'Visitez la ville bleue et ses environs enchanteurs.',
    country: 'Maroc',
    location: 'Chefchaouen',
    duration: 3,
    price: 3100,
    src: 'https://images.unsplash.com/photo-1695601758107-cffeeceace44?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Excursion en vélo',
    description: 'Balades à vélo pour explorer la campagne marocaine.',
    country: 'Maroc',
    location: 'Vallee de l’Ourika',
    duration: 3,
    price: 2900,
    src: 'https://images.unsplash.com/photo-1638278958562-be34bf8946c3?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Excursion en montagne',
    description: 'Randonnée et découverte des villages berbères traditionnels.',
    country: 'Maroc',
    location: 'Rif',
    duration: 5,
    price: 3600,
    src: 'https://images.unsplash.com/photo-1732468963609-4d1b03b173b4?q=80&w=689&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Visite des kasbahs',
    description:
      'Explorez les célèbres kasbahs et villages fortifiés marocains.',
    country: 'Maroc',
    location: 'Ouarzazate',
    duration: 4,
    price: 3300,
    src: 'https://images.unsplash.com/photo-1668437711042-cba07f0af9d9?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Circuit historique',
    description: 'Visitez les sites historiques majeurs du Maroc.',
    country: 'Maroc',
    location: 'Rabat',
    duration: 4,
    price: 3400,
    src: 'https://images.unsplash.com/photo-1737921650058-200b00360ada?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Pêche en mer',
    description: 'Journée de pêche en mer au départ d’Essaouira.',
    country: 'Maroc',
    location: 'Essaouira',
    duration: 1,
    price: 1200,
    src: 'https://images.unsplash.com/photo-1646590639310-2ae4412e9248?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Camping dans le désert',
    description: 'Nuit sous les étoiles dans un camp traditionnel berbère.',
    country: 'Maroc',
    location: 'Sahara',
    duration: 2,
    price: 2200,
    src: 'https://plus.unsplash.com/premium_photo-1699534404114-43e162f927fb?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Observation des étoiles',
    description: 'Nuits d’observation astronomique dans le désert.',
    country: 'Maroc',
    location: 'Sahara',
    duration: 2,
    price: 1900,
    src: 'https://images.unsplash.com/photo-1643271963369-e5d2f5bdddf5?q=80&w=1035&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Randonnée en montagne',
    description:
      'Explorez des sentiers sauvages avec des vues imprenables sur les sommets.',
    country: 'Maroc',
    location: 'Atlas',
    duration: 5,
    price: 3500,
    src: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
  },
  {
    title: 'Séjour balnéaire',
    description:
      'Relaxation et activités nautiques dans une station balnéaire moderne.',
    country: 'Maroc',
    location: 'Essaouira',
    duration: 7,
    price: 4100,
    src: 'https://images.unsplash.com/photo-1635356179268-710bde4489f7?q=80&w=736&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Séjour à Marrakech',
    description: 'Plongez dans l’ambiance des marchés traditionnels marocains.',
    country: 'Maroc',
    location: 'Marrakech',
    duration: 3,
    price: 2900,
    src: 'https://images.unsplash.com/photo-1585004607620-fb4c44331e73?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Festival et musique',
    description: 'Participez aux événements culturels et musicaux locaux.',
    country: 'Maroc',
    location: 'Essaouira',
    duration: 4,
    price: 3800,
    src: 'https://images.unsplash.com/photo-1519518061520-141a3aaba0a0?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Découverte des cascades',
    description: 'Randonnée vers les plus belles cascades du pays.',
    country: 'Maroc',
    location: 'Ouzoud',
    duration: 3,
    price: 3000,
    src: 'https://images.unsplash.com/photo-1585213303822-f19214012600?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Plongée sous-marine',
    description: 'Explorez la richesse sous-marine de la Méditerranée.',
    country: 'Maroc',
    location: 'Al Hoceima',
    duration: 4,
    price: 4100,
    src: 'https://images.unsplash.com/photo-1654980475915-77c47c936a7a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Visite culturelle',
    description:
      'Découvrez les trésors historiques et architecturaux du Maroc.',
    country: 'Maroc',
    location: 'Marrakech',
    duration: 4,
    price: 3000,
    src: 'https://images.unsplash.com/photo-1559925523-10de9e23cf90?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Safari dans le désert',
    description:
      'Aventurez-vous dans les dunes dorées pour une expérience unique.',
    country: 'Maroc',
    location: 'Sahara',
    duration: 6,
    price: 5000,
    src: 'https://images.unsplash.com/photo-1697723779446-0feb51d762d0?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Exploration urbaine',
    description: 'Immersion dans la vie citadine et ses secrets.',
    country: 'Maroc',
    location: 'Casablanca',
    duration: 4,
    price: 3200,
    src: 'https://images.unsplash.com/photo-1707084398977-4d5035e1cba4?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Balade en chameau',
    description: 'Découvrez le désert à dos de chameau au coucher du soleil.',
    country: 'Maroc',
    location: 'Merzouga',
    duration: 2,
    price: 1800,
    src: 'https://images.unsplash.com/photo-1525953771362-cdbcffdcad13?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Aventure en quad',
    description: 'Excursions en quad à travers les paysages désertiques.',
    country: 'Maroc',
    location: 'Merzouga',
    duration: 3,
    price: 2600,
    src: 'https://images.unsplash.com/photo-1580761338251-16bfec2343ef?q=80&w=1061&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Tour en montgolfière',
    description: 'Survolez les paysages marocains en ballon à air chaud.',
    country: 'Maroc',
    location: 'Marrakech',
    duration: 1,
    price: 4500,
    src: 'https://images.unsplash.com/photo-1750008415039-65c10dcbb4a5?q=80&w=1175&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Trek dans le désert',
    description: 'Marchez au cœur du désert avec un guide expérimenté.',
    country: 'Maroc',
    location: 'Sahara',
    duration: 6,
    price: 5200,
    src: 'https://images.unsplash.com/photo-1504957640760-83fa72f80123?q=80&w=1147&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Visite artisanale',
    description: 'Rencontrez les artisans et découvrez leurs savoir-faire.',
    country: 'Maroc',
    location: 'Fès',
    duration: 3,
    price: 2700,
    src: 'https://images.unsplash.com/photo-1542366172-ffed3bebb7db?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'thththth',
    description: 'thththth',
    country: 'Maroc',
    location: 'thththth',
    duration: 0,
    price: 0,
    src: 'https://images.unsplash.com/photo-1598257128753-a04bd0f846cd?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
];

const destinations = [
  {
    title: 'Tour gastronomique',
    description: 'Savourez les meilleures spécialités marocaines.',
    country: 'Maroc',
    location: 'Fès',
    duration: 3,
    price: 2800,
    herbergement: true,
    wifi: true,
    petit_dej: false,
    Transfert: false,
    nb_personnes: 20,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1661081988119-58e40ee39201?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Aventure en forêt',
    description:
      'Balades et découvertes dans les forêts luxuriantes du d`ifran.',
    country: 'Maroc',
    location: 'Ifran',
    duration: 5,
    price: 3900,
    herbergement: true,
    wifi: false,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 12,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1611358382200-5baf13de1b40?q=80&w=1633&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Séjour dans un riad',
    description:
      'Vivez l’expérience authentique d’un hébergement traditionnel.',
    country: 'Maroc',
    location: 'Médina de Fès',
    duration: 3,
    price: 2500,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: false,
    nb_personnes: 8,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1671181087708-be3050f1974e?q=80&w=740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Sports nautiques',
    description: 'Plongée, kitesurf et paddle dans les eaux de Tamraght.',
    country: 'Maroc',
    location: 'Tamraght',
    duration: 5,
    price: 3700,
    herbergement: true,
    wifi: false,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 15,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1537174621888-eba6137cf6c9?q=80&w=2080&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Séjour bien-être',
    description: 'Spa, hammams et relaxation dans un cadre authentique.',
    country: 'Maroc',
    location: 'Agadir',
    duration: 5,
    price: 4200,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: false,
    nb_personnes: 10,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1600289730889-17f9ad4c38f0?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Excursion à Chefchaouen',
    description: 'Visitez la ville bleue et ses environs enchanteurs.',
    country: 'Maroc',
    location: 'Chefchaouen',
    duration: 3,
    price: 3100,
    herbergement: true,
    wifi: true,
    petit_dej: false,
    Transfert: true,
    nb_personnes: 18,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1695601758107-cffeeceace44?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Excursion en vélo',
    description: 'Balades à vélo pour explorer la campagne marocaine.',
    country: 'Maroc',
    location: 'Vallee de l’Ourika',
    duration: 3,
    price: 2900,
    herbergement: false,
    wifi: false,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 7,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1638278958562-be34bf8946c3?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Excursion en montagne',
    description: 'Randonnée et découverte des villages berbères traditionnels.',
    country: 'Maroc',
    location: 'Rif',
    duration: 5,
    price: 3600,
    herbergement: true,
    wifi: false,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 9,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1732468963609-4d1b03b173b4?q=80&w=689&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Visite des kasbahs',
    description:
      'Explorez les célèbres kasbahs et villages fortifiés marocains.',
    country: 'Maroc',
    location: 'Ouarzazate',
    duration: 4,
    price: 3300,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: false,
    nb_personnes: 14,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1668437711042-cba07f0af9d9?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Circuit historique',
    description: 'Visitez les sites historiques majeurs du Maroc.',
    country: 'Maroc',
    location: 'Rabat',
    duration: 4,
    price: 3400,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 16,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1737921650058-200b00360ada?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Pêche en mer',
    description: 'Journée de pêche en mer au départ d’Essaouira.',
    country: 'Maroc',
    location: 'Essaouira',
    duration: 1,
    price: 1200,
    herbergement: false,
    wifi: false,
    petit_dej: false,
    Transfert: true,
    nb_personnes: 6,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1646590639310-2ae4412e9248?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Camping dans le désert',
    description: 'Nuit sous les étoiles dans un camp traditionnel berbère.',
    country: 'Maroc',
    location: 'Sahara',
    duration: 2,
    price: 2200,
    herbergement: true,
    wifi: false,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 10,
    type: 'voyage',
    src: 'https://plus.unsplash.com/premium_photo-1699534404114-43e162f927fb?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Observation des étoiles',
    description: 'Nuits d’observation astronomique dans le désert.',
    country: 'Maroc',
    location: 'Sahara',
    duration: 2,
    price: 1900,
    herbergement: false,
    wifi: false,
    petit_dej: false,
    Transfert: true,
    nb_personnes: 5,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1643271963369-e5d2f5bdddf5?q=80&w=1035&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Randonnée en montagne',
    description:
      'Explorez des sentiers sauvages avec des vues imprenables sur les sommets.',
    country: 'Maroc',
    location: 'Atlas',
    duration: 5,
    price: 3500,
    herbergement: true,
    wifi: false,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 10,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
  },
  {
    title: 'Séjour balnéaire',
    description:
      'Relaxation et activités nautiques dans une station balnéaire moderne.',
    country: 'Maroc',
    location: 'Essaouira',
    duration: 7,
    price: 4100,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: false,
    nb_personnes: 15,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1635356179268-710bde4489f7?q=80&w=736&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Séjour à Marrakech',
    description: 'Plongez dans l’ambiance des marchés traditionnels marocains.',
    country: 'Maroc',
    location: 'Marrakech',
    duration: 3,
    price: 2900,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 20,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1585004607620-fb4c44331e73?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Festival et musique',
    description: 'Participez aux événements culturels et musicaux locaux.',
    country: 'Maroc',
    location: 'Essaouira',
    duration: 4,
    price: 3800,
    herbergement: true,
    wifi: false,
    petit_dej: false,
    Transfert: true,
    nb_personnes: 25,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1519518061520-141a3aaba0a0?q=80&w=1171&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Découverte des cascades',
    description: 'Randonnée vers les plus belles cascades du pays.',
    country: 'Maroc',
    location: 'Ouzoud',
    duration: 3,
    price: 3000,
    herbergement: true,
    wifi: false,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 12,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1585213303822-f19214012600?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Plongée sous-marine',
    description: 'Explorez la richesse sous-marine de la Méditerranée.',
    country: 'Maroc',
    location: 'Al Hoceima',
    duration: 4,
    price: 4100,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: false,
    nb_personnes: 8,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1654980475915-77c47c936a7a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Visite culturelle',
    description:
      'Découvrez les trésors historiques et architecturaux du Maroc.',
    country: 'Maroc',
    location: 'Marrakech',
    duration: 4,
    price: 3000,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 18,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1559925523-10de9e23cf90?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Safari dans le désert',
    description:
      'Aventurez-vous dans les dunes dorées pour une expérience unique.',
    country: 'Maroc',
    location: 'Sahara',
    duration: 6,
    price: 5000,
    herbergement: true,
    wifi: false,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 10,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1697723779446-0feb51d762d0?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Exploration urbaine',
    description: 'Immersion dans la vie citadine et ses secrets.',
    country: 'Maroc',
    location: 'Casablanca',
    duration: 4,
    price: 3200,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 22,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1707084398977-4d5035e1cba4?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Balade en chameau',
    description: 'Découvrez le désert à dos de chameau au coucher du soleil.',
    country: 'Maroc',
    location: 'Merzouga',
    duration: 2,
    price: 1800,
    herbergement: false,
    wifi: false,
    petit_dej: false,
    Transfert: true,
    nb_personnes: 7,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1525953771362-cdbcffdcad13?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Aventure en quad',
    description: 'Excursions en quad à travers les paysages désertiques.',
    country: 'Maroc',
    location: 'Merzouga',
    duration: 3,
    price: 2600,
    herbergement: false,
    wifi: false,
    petit_dej: false,
    Transfert: true,
    nb_personnes: 9,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1580761338251-16bfec2343ef?q=80&w=1061&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Tour en montgolfière',
    description: 'Survolez les paysages marocains en ballon à air chaud.',
    country: 'Maroc',
    location: 'Marrakech',
    duration: 1,
    price: 4500,
    herbergement: false,
    wifi: false,
    petit_dej: false,
    Transfert: true,
    nb_personnes: 4,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1750008415039-65c10dcbb4a5?q=80&w=1175&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Trek dans le désert',
    description: 'Marchez au cœur du désert avec un guide expérimenté.',
    country: 'Maroc',
    location: 'Sahara',
    duration: 6,
    price: 5200,
    herbergement: true,
    wifi: false,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 6,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1504957640760-83fa72f80123?q=80&w=1147&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Visite artisanale',
    description: 'Rencontrez les artisans et découvrez leurs savoir-faire.',
    country: 'Maroc',
    location: 'Fès',
    duration: 3,
    price: 2700,
    herbergement: true,
    wifi: true,
    petit_dej: false,
    Transfert: true,
    nb_personnes: 15,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1542366172-ffed3bebb7db?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'thththth',
    description: 'Ceci est une description aléatoire pour thththth.',
    country: 'Maroc',
    location: 'Quelque part au Maroc',
    duration: 4,
    price: 2500,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: false,
    nb_personnes: 10,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1598257128753-a04bd0f846cd?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    title: 'Omra Ramadan 2025',
    description:
      'Profitez d’un séjour spirituel à La Mecque pendant le mois sacré.',
    country: 'Arabie Saoudite',
    location: 'La Mecque',
    duration: 15,
    price: 18500,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 40,
    type: 'omra_hajj',
    src: 'https://images.unsplash.com/photo-1591004272853-1462c050dca8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aGFqanxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    title: 'Hajj 2025 - Formule Confort',
    description:
      'Un accompagnement complet pour un Hajj serein avec guide francophone.',
    country: 'Arabie Saoudite',
    location: 'La Mecque & Médine',
    duration: 21,
    price: 49000,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 50,
    type: 'omra_hajj',
    src: 'https://images.unsplash.com/photo-1605553378313-22d0dc541393?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGhhamp8ZW58MHx8MHx8fDA%3D',
  },
  {
    title: 'Séjour Omra Express',
    description:
      'Un séjour court mais intense pour effectuer votre Omra en toute sérénité.',
    country: 'Arabie Saoudite',
    location: 'La Mecque',
    duration: 7,
    price: 12500,
    herbergement: true,
    wifi: false,
    petit_dej: false,
    Transfert: true,
    nb_personnes: 20,
    type: 'omra_hajj',
    src: 'https://images.unsplash.com/photo-1582373297833-17c72d7bc9ed?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDN8fGhhamp8ZW58MHx8MHx8fDA%3D',
  },
  {
    title: 'Hôtel 4* à Médine',
    description: 'Confort et proximité de la mosquée du Prophète.',
    country: 'Arabie Saoudite',
    location: 'Médine',
    duration: 3,
    price: 850,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: false,
    nb_personnes: 2,
    type: 'omra_hajj',
    src: 'https://images.unsplash.com/photo-1692566123227-0f68f1b9dac6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWFkaW5hfGVufDB8fDB8fHww',
  },
  {
    title: 'Hôtel 5* à La Mecque',
    description: 'Vue directe sur la Kaaba, services haut de gamme.',
    country: 'Arabie Saoudite',
    location: 'La Mecque',
    duration: 5,
    price: 1500,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 2,
    type: 'omra_hajj',
    src: 'https://images.unsplash.com/photo-1624171156512-077b7a150e6c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzZ8fGhhamolMjBtZWNjYXxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    title: 'Omra Février 2025 - Groupe Jeunes',
    description: 'Un voyage spirituel encadré pour les jeunes adultes.',
    country: 'Arabie Saoudite',
    location: 'La Mecque & Médine',
    duration: 10,
    price: 13900,
    herbergement: true,
    wifi: true,
    petit_dej: false,
    Transfert: true,
    nb_personnes: 30,
    type: 'omra_hajj',
    src: 'https://images.unsplash.com/photo-1723512414375-45ff0ed80afd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjB8fGhhamolMjBtZWNjYXxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    title: 'Séjour Hajj Luxe',
    description:
      'Expérience premium avec hébergement 5 étoiles et transferts privés.',
    country: 'Arabie Saoudite',
    location: 'La Mecque & Médine',
    duration: 25,
    price: 65000,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 35,
    type: 'omra_hajj',
    src: 'https://images.unsplash.com/photo-1588652620344-49032f0404f6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTV8fGhhamolMjBtZWNjYXxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    title: 'Hôtel économique à Médine',
    description: 'Idéal pour les courts séjours à petit budget.',
    country: 'Arabie Saoudite',
    location: 'Médine',
    duration: 2,
    price: 500,
    herbergement: true,
    wifi: false,
    petit_dej: false,
    Transfert: false,
    nb_personnes: 2,
    type: 'omra_hajj',
    src: 'https://images.unsplash.com/photo-1565828480412-f95f33fe9e70?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDh8fGhhamolMjBtZWNjYXxlbnwwfHwwfHx8MA%3D%3D',
  },
  {
    title: 'Hôtel Riad Andalou',
    description:
      'Un riad traditionnel au cœur de la médina avec tout le confort moderne.',
    country: 'Maroc',
    location: 'Marrakech',
    duration: 3,
    price: 1200,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: false,
    nb_personnes: 2,
    type: 'hotel',
    src: '',
  },
  {
    title: 'Hôtel Merzouga Dunes',
    description:
      'Un séjour au pied des dunes, idéal pour une expérience saharienne.',
    country: 'Maroc',
    location: 'Merzouga',
    duration: 2,
    price: 800,
    herbergement: true,
    wifi: false,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 2,
    type: 'hotel',
    src: '',
  },
  {
    title: 'Hôtel La Baie Blanche',
    description: 'Vue imprenable sur la mer avec accès direct à la plage.',
    country: 'Tunisie',
    location: 'Hammamet',
    duration: 4,
    price: 1500,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 2,
    type: 'hotel',
    src: '',
  },
  {
    title: 'Hôtel Palm Djerba',
    description: 'Ambiance relaxante dans un cadre idyllique à Djerba.',
    country: 'Tunisie',
    location: 'Djerba',
    duration: 5,
    price: 1100,
    herbergement: true,
    wifi: true,
    petit_dej: false,
    Transfert: false,
    nb_personnes: 2,
    type: 'hotel',
    src: '',
  },
  {
    title: 'Hôtel Desert Camp',
    description: 'Campement de luxe dans le désert avec tentes climatisées.',
    country: 'Maroc',
    location: 'Zagora',
    duration: 2,
    price: 950,
    herbergement: true,
    wifi: false,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 2,
    type: 'hotel',
    src: '',
  },
  {
    title: 'Hôtel Médina Palace',
    description: 'Établissement 5 étoiles moderne à proximité de la médina.',
    country: 'Maroc',
    location: 'Fès',
    duration: 3,
    price: 1700,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 2,
    type: 'hotel',
    src: '',
  },
  {
    title: 'Hôtel Al Qasr',
    description:
      'Cadre luxueux et service haut de gamme en plein centre-ville.',
    country: 'Émirats Arabes Unis',
    location: 'Dubaï',
    duration: 4,
    price: 3200,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: true,
    nb_personnes: 2,
    type: 'hotel',
    src: '',
  },
  {
    title: 'Hôtel Oasis Relax',
    type: 'hotel',
    description: 'Parfait pour une escapade détente avec spa et piscine.',
    country: 'Maroc',
    location: 'Agadir',
    duration: 3,
    price: 1400,
    herbergement: true,
    wifi: true,
    petit_dej: true,
    Transfert: false,
    nb_personnes: 2,
    type: 'hotel',
    src: '',
  },
];

const tour = [
  {
    _id: '686ba2fa8a2d2161499d3706',
    title: 'Tour gastronomique',
    description: 'Savourez les meilleures spécialités marocaines.',
    country: 'Maroc',
    location: 'Fès',
    duration: 3,
    price: 2800,
    herbergement: true,
    petit_dej: false,
    Transfert: false,
    nb_personnes: 20,
    type: 'voyage',
    src: 'https://images.unsplash.com/photo-1661081988119-58e40ee39201?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    __v: 0,
    id: '686ba2fa8a2d2161499d3706',
  },
];
const user = [
  {
    username: 'ilyas_125',
    email: 'ilyas@gmail.com',
    password: '123456789',
    role: 'user',
  },
];
fetch('http://localhost:5000/api/users', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify(user ),
})
  .then((res) => res.json())
  .then((data) => {
    console.log('Seed successful:');
  })
  .catch((err) => {
    console.error('Error seeding data:', err);
  });



