import Hebergement from '../models/Hebergement.js';
import formatDocument from '../utils/fomatDoc.js';

export const getHebergement = async (req, res) => {
  try {
    const { pagination, sortBy, filters } = req;
    const limit = pagination.limit;
    const skip = pagination.skip;
    const hebergements = await Hebergement.find(filters)
      .sort(sortBy)
      .skip(skip)
      .limit(limit);
    const total = await Hebergement.countDocuments(filters);
    if (!hebergements)
      return res.status(404).json({ error: 'hebergements not found' });
    const data = hebergements.map(formatDocument);
    res.status(200).json({ hebergements:data, total: total });
  } catch (error) {
    res.status(500).json({error});
  }
};

export const getHebergementById = async (req, res) => {
  try {
    const hebergement = await Hebergement.findById(req.params.id);
    if (!hebergement)
      return res.status(404).json({ error: 'hebergement not found' });
    const data = formatDocument(hebergement);
    res.status(200).json(data);
  } catch (error) {
    res.status(500).json({ error: 'Failed to get Hebergement' });
  }
};

export const createHebergement = async (req, res) => {
  try {
    const created = await Hebergement.create(req.body);
    if (!created)
      return res.status(400).json({ error: 'Hebergement not created' });
    const data = formatDocument(created);
    res.status(201).json(data);
  } catch (error) {
     res.status(500).json({error});
  }
};

export const deleteHebergement = async (req, res) => {
  try {
    const deleted = await Hebergement.findByIdAndDelete(req.params.id);
    if (!deleted)
      return res.status(400).json({ error: 'Hebergement not deleted' });
    const data = formatDocument(deleted);
    res.status(200).json(data);
  } catch (error) {
    res.status(500).json({ error: 'Failed to delete Hebergement' });
  }
};

export const updateHebergement = async (req, res) => {
  try {
    const updated = await Hebergement.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true }
    );
    if (!updated)
      return res.status(400).json({ error: 'Hebergement not updated' });
    const data = formatDocument(updated);
    res.status(200).json(data);
  } catch (error) {
    res.status(500).json({ error: 'Failed to update Hebergement' });
  }
};

export const deleteAll = async (req, res) => {
  try {
    const deleted = await Hebergement.deleteMany();
    res.status(200).json({ message: 'everything is deleted' });
  } catch (error) {
    res.status(500).json({ error: 'failed to delete all' });
  }
};
const seedHebergements = [
  {
    name: "Hôtel Atlas Marrakech",
    type: "hotel",
    slug: "hotel-atlas-marrakech",
    note: 4.5,
    country: "Maroc",
    city: "Marrakech",
    availability: true,
    address: "15 Avenue Mohamed V",
    services: ["wifi", "pool", "spa", "gym", "restaurant"],
    prix_basique: 300,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 320 },
      { typeChambre: "double", typeLit: "twin", prix: 310 },
      { typeChambre: "single", typeLit: "single", prix: 300 },
    ],
    rating: 4.5,
    BreakfastIncluded: true,
    proximity: 2,
    description: "Un hôtel luxueux avec piscine et spa au cœur de Marrakech.",
    images: [],
    thumbnail: "",
    tags: ["luxury", "spa", "pool"],
    status: "libre",
  },
  {
    name: "Riad Alhambra",
    type: "riad",
    slug: "riad-alhambra",
    note: 4.1,
    country: "Maroc",
    city: "Marrakech",
    availability: true,
    address: "3 Rue Bab Doukkala",
    services: ["wifi", "parking", "laundry", "restaurant"],
    prix_basique: 180,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 185 },
      { typeChambre: "single", typeLit: "single", prix: 180 },
      { typeChambre: "quadruple", typeLit: "single", prix: 320 },
    ],
    rating: 4.1,
    BreakfastIncluded: false,
    proximity: 3,
    description: "Riad traditionnel avec une ambiance chaleureuse.",
    images: [],
    thumbnail: "",
    tags: ["traditional", "cozy"],
    status: "privé",
  },
  {
    name: "Auberge Kasbah",
    type: "auberge",
    slug: "auberge-kasbah",
    note: 3.9,
    country: "Maroc",
    city: "Merzouga",
    availability: true,
    address: "Route du Désert",
    services: ["wifi", "restaurant", "parking"],
    prix_basique: 150,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 155 },
      { typeChambre: "single", typeLit: "single", prix: 150 },
      { typeChambre: "quadruple", typeLit: "single", prix: 280 },
    ],
    rating: 3.9,
    BreakfastIncluded: true,
    proximity: 7,
    description: "Auberge authentique dans le désert avec vue imprenable.",
    images: [],
    thumbnail: "",
    tags: ["desert", "authentic"],
    status: "libre",
  },
  {
    name: "Hôtel Sahara Dunes",
    type: "hotel",
    slug: "hotel-sahara-dunes",
    note: 4.3,
    country: "Maroc",
    city: "Erfoud",
    availability: true,
    address: "12 Route des Dunes",
    services: ["wifi", "pool", "gym", "restaurant"],
    prix_basique: 220,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 225 },
      { typeChambre: "double", typeLit: "twin", prix: 220 },
      { typeChambre: "single", typeLit: "single", prix: 215 },
    ],
    rating: 4.3,
    BreakfastIncluded: true,
    proximity: 4,
    description: "Hôtel moderne avec piscine et salle de sport.",
    images: [],
    thumbnail: "",
    tags: ["modern", "pool"],
    status: "privé",
  },
  {
    name: "Riad des Fleurs",
    type: "riad",
    slug: "riad-des-fleurs",
    note: 4.0,
    country: "Maroc",
    city: "Fès",
    availability: true,
    address: "7 Rue des Fleurs",
    services: ["wifi", "parking", "laundry"],
    prix_basique: 190,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 195 },
      { typeChambre: "single", typeLit: "single", prix: 190 },
      { typeChambre: "quadruple", typeLit: "single", prix: 310 },
    ],
    rating: 4.0,
    BreakfastIncluded: false,
    proximity: 3,
    description: "Riad paisible avec jardin et décoration traditionnelle.",
    images: [],
    thumbnail: "",
    tags: ["peaceful", "traditional"],
    status: "libre",
  },
  {
    name: "Auberge du Lac",
    type: "auberge",
    slug: "auberge-du-lac",
    note: 3.7,
    country: "Maroc",
    city: "Ouarzazate",
    availability: true,
    address: "Route du Lac",
    services: ["wifi", "restaurant", "parking"],
    prix_basique: 160,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 165 },
      { typeChambre: "single", typeLit: "single", prix: 160 },
      { typeChambre: "quadruple", typeLit: "single", prix: 290 },
    ],
    rating: 3.7,
    BreakfastIncluded: true,
    proximity: 5,
    description: "Auberge paisible près du lac avec ambiance conviviale.",
    images: [],
    thumbnail: "",
    tags: ["lake", "peaceful"],
    status: "privé",
  },
  {
    name: "Hôtel Majestic",
    type: "hotel",
    slug: "hotel-majestic",
    note: 4.5,
    country: "Maroc",
    city: "Casablanca",
    availability: true,
    address: "Rue Majestic 7",
    services: ["wifi", "pool", "gym", "restaurant"],
    prix_basique: 220,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 230 },
      { typeChambre: "double", typeLit: "twin", prix: 225 },
      { typeChambre: "single", typeLit: "single", prix: 220 },
    ],
    rating: 4.5,
    BreakfastIncluded: true,
    proximity: 5,
    description: "Hôtel luxueux en centre-ville.",
    images: [],
    thumbnail: "",
    tags: ["luxury", "central"],
    status: "libre",
  },
  {
    name: "Riad Zen",
    type: "riad",
    slug: "riad-zen",
    note: 4.2,
    country: "Maroc",
    city: "Chefchaouen",
    availability: true,
    address: "14 Rue Bleu",
    services: ["wifi", "laundry", "parking"],
    prix_basique: 175,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 180 },
      { typeChambre: "single", typeLit: "single", prix: 175 },
      { typeChambre: "quadruple", typeLit: "single", prix: 310 },
    ],
    rating: 4.2,
    BreakfastIncluded: false,
    proximity: 6,
    description: "Riad calme avec vue sur la montagne.",
    images: [],
    thumbnail: "",
    tags: ["calm", "view"],
    status: "privé",
  },
  {
    name: "Auberge des Montagnes",
    type: "auberge",
    slug: "auberge-des-montagnes",
    note: 4.1,
    country: "Maroc",
    city: "Ifrane",
    availability: true,
    address: "5 Route de la Forêt",
    services: ["wifi", "restaurant", "parking"],
    prix_basique: 170,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 175 },
      { typeChambre: "single", typeLit: "single", prix: 170 },
      { typeChambre: "quadruple", typeLit: "single", prix: 300 },
    ],
    rating: 4.1,
    BreakfastIncluded: true,
    proximity: 4,
    description: "Auberge confortable au cœur des montagnes.",
    images: [],
    thumbnail: "",
    tags: ["mountain", "cozy"],
    status: "libre",
  },
  {
    name: "Hôtel Le Palmier",
    type: "hotel",
    slug: "hotel-le-palmier",
    note: 4.4,
    country: "Maroc",
    city: "Meknès",
    availability: true,
    address: "12 Avenue des Palmiers",
    services: ["wifi", "gym", "restaurant"],
    prix_basique: 195,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 205 },
      { typeChambre: "double", typeLit: "twin", prix: 200 },
      { typeChambre: "single", typeLit: "single", prix: 195 },
    ],
    rating: 4.4,
    BreakfastIncluded: true,
    proximity: 3,
    description: "Hôtel moderne au centre-ville de Meknès.",
    images: [],
    thumbnail: "",
    tags: ["modern", "central"],
    status: "privé",
  },
  {
    name: "Riad El Medina",
    type: "riad",
    slug: "riad-el-medina",
    note: 4.0,
    country: "Maroc",
    city: "Fès",
    availability: true,
    address: "8 Rue de la Medina",
    services: ["wifi", "parking", "laundry"],
    prix_basique: 185,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 190 },
      { typeChambre: "single", typeLit: "single", prix: 185 },
      { typeChambre: "quadruple", typeLit: "single", prix: 320 },
    ],
    rating: 4.0,
    BreakfastIncluded: false,
    proximity: 4,
    description: "Riad traditionnel avec ambiance chaleureuse.",
    images: [],
    thumbnail: "",
    tags: ["traditional", "warm"],
    status: "libre",
  },
  {
    name: "Hôtel Oasis Bleu",
    type: "hotel",
    slug: "hotel-oasis-bleu",
    note: 4.6,
    country: "Maroc",
    city: "Agadir",
    availability: true,
    address: "10 Boulevard de la Plage",
    services: ["wifi", "pool", "gym", "restaurant"],
    prix_basique: 230,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 240 },
      { typeChambre: "double", typeLit: "twin", prix: 235 },
      { typeChambre: "single", typeLit: "single", prix: 230 },
    ],
    rating: 4.6,
    BreakfastIncluded: true,
    proximity: 1,
    description: "Hôtel moderne avec piscine et spa.",
    images: [],
    thumbnail: "",
    tags: ["modern", "pool"],
    status: "privé",
  },
  {
    name: "Riad Jardin Secret",
    type: "riad",
    slug: "riad-jardin-secret",
    note: 4.3,
    country: "Maroc",
    city: "Marrakech",
    availability: true,
    address: "33 Rue des Jardins",
    services: ["wifi", "parking", "laundry"],
    prix_basique: 190,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 195 },
      { typeChambre: "single", typeLit: "single", prix: 190 },
      { typeChambre: "quadruple", typeLit: "single", prix: 340 },
    ],
    rating: 4.3,
    BreakfastIncluded: false,
    proximity: 3,
    description: "Riad charmant avec jardin paisible.",
    images: [],
    thumbnail: "",
    tags: ["quiet", "charming"],
    status: "libre",
  },
  {
    name: "Riad Safran",
    type: "riad",
    slug: "riad-safran",
    note: 4.0,
    country: "Maroc",
    city: "Essaouira",
    availability: true,
    address: "24 Rue des Saules",
    services: ["wifi", "parking", "laundry", "pet_friendly"],
    prix_basique: 180,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 185 },
      { typeChambre: "single", typeLit: "single", prix: 180 },
      { typeChambre: "quadruple", typeLit: "single", prix: 310 },
    ],
    rating: 4.0,
    BreakfastIncluded: true,
    proximity: 2,
    description: "Riad agréable proche de la plage et des souks.",
    images: [],
    thumbnail: "",
    tags: ["beach", "souks"],
    status: "privé",
  },
  {
    name: "Hôtel Le Casbah",
    type: "hotel",
    slug: "hotel-le-casbah",
    note: 4.4,
    country: "Maroc",
    city: "Ouarzazate",
    availability: true,
    address: "1 Avenue des Palmiers",
    services: ["wifi", "pool", "restaurant", "gym"],
    prix_basique: 210,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 215 },
      { typeChambre: "double", typeLit: "twin", prix: 210 },
      { typeChambre: "single", typeLit: "single", prix: 205 },
    ],
    rating: 4.4,
    BreakfastIncluded: true,
    proximity: 4,
    description: "Hôtel avec piscine et centre de remise en forme.",
    images: [],
    thumbnail: "",
    tags: ["pool", "fitness"],
    status: "libre",
  },
  {
    name: "Auberge du Soleil",
    type: "auberge",
    slug: "auberge-du-soleil",
    note: 3.8,
    country: "Maroc",
    city: "Taroudant",
    availability: true,
    address: "Route du Soleil",
    services: ["wifi", "restaurant", "parking"],
    prix_basique: 155,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 160 },
      { typeChambre: "single", typeLit: "single", prix: 155 },
      { typeChambre: "quadruple", typeLit: "single", prix: 290 },
    ],
    rating: 3.8,
    BreakfastIncluded: false,
    proximity: 6,
    description: "Auberge calme avec restaurant traditionnel.",
    images: [],
    thumbnail: "",
    tags: ["calm", "traditional"],
    status: "privé",
  },
  {
    name: "Hôtel Riviera",
    type: "hotel",
    slug: "hotel-riviera",
    note: 4.3,
    country: "Maroc",
    city: "Tanger",
    availability: true,
    address: "5 Boulevard de la Mer",
    services: ["wifi", "pool", "gym", "restaurant"],
    prix_basique: 225,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 230 },
      { typeChambre: "double", typeLit: "twin", prix: 225 },
      { typeChambre: "single", typeLit: "single", prix: 220 },
    ],
    rating: 4.3,
    BreakfastIncluded: true,
    proximity: 2,
    description: "Hôtel avec vue sur la mer et piscine extérieure.",
    images: [],
    thumbnail: "",
    tags: ["sea_view", "pool"],
    status: "libre",
  },
  {
    name: "Riad Lalla",
    type: "riad",
    slug: "riad-lalla",
    note: 4.1,
    country: "Maroc",
    city: "Essaouira",
    availability: true,
    address: "11 Rue Lalla",
    services: ["wifi", "parking", "laundry"],
    prix_basique: 185,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 190 },
      { typeChambre: "single", typeLit: "single", prix: 185 },
      { typeChambre: "quadruple", typeLit: "single", prix: 320 },
    ],
    rating: 4.1,
    BreakfastIncluded: false,
    proximity: 3,
    description: "Riad charmant avec terrasse ensoleillée.",
    images: [],
    thumbnail: "",
    tags: ["sunny", "terrace"],
    status: "privé",
  },
  {
    name: "Auberge Tizi",
    type: "auberge",
    slug: "auberge-tizi",
    note: 3.6,
    country: "Maroc",
    city: "Tizi n'Test",
    availability: true,
    address: "Route de la Montagne",
    services: ["wifi", "restaurant", "parking"],
    prix_basique: 145,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 150 },
      { typeChambre: "single", typeLit: "single", prix: 145 },
      { typeChambre: "quadruple", typeLit: "single", prix: 270 },
    ],
    rating: 3.6,
    BreakfastIncluded: true,
    proximity: 7,
    description: "Auberge traditionnelle en montagne.",
    images: [],
    thumbnail: "",
    tags: ["mountain", "traditional"],
    status: "libre",
  },
  {
    name: "Hôtel Grand Atlas",
    type: "hotel",
    slug: "hotel-grand-atlas",
    note: 4.5,
    country: "Maroc",
    city: "Ifrane",
    availability: true,
    address: "20 Boulevard Central",
    services: ["wifi", "pool", "spa", "gym", "restaurant"],
    prix_basique: 310,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 320 },
      { typeChambre: "double", typeLit: "twin", prix: 315 },
      { typeChambre: "single", typeLit: "single", prix: 310 },
    ],
    rating: 4.5,
    BreakfastIncluded: true,
    proximity: 1,
    description: "Hôtel luxueux avec spa et piscine chauffée.",
    images: [],
    thumbnail: "",
    tags: ["luxury", "spa", "pool"],
    status: "privé",
  },
  {
    name: "Riad Saphir",
    type: "riad",
    slug: "riad-saphir",
    note: 4.2,
    country: "Maroc",
    city: "Marrakech",
    availability: true,
    address: "8 Rue Saphir",
    services: ["wifi", "laundry", "parking"],
    prix_basique: 180,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 185 },
      { typeChambre: "single", typeLit: "single", prix: 180 },
      { typeChambre: "quadruple", typeLit: "single", prix: 305 },
    ],
    rating: 4.2,
    BreakfastIncluded: false,
    proximity: 3,
    description: "Riad confortable proche des souks.",
    images: [],
    thumbnail: "",
    tags: ["comfort", "souks"],
    status: "libre",
  },
  {
    name: "Auberge Rose",
    type: "auberge",
    slug: "auberge-rose",
    note: 3.9,
    country: "Maroc",
    city: "Chefchaouen",
    availability: true,
    address: "10 Rue des Roses",
    services: ["wifi", "restaurant", "parking"],
    prix_basique: 160,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 165 },
      { typeChambre: "single", typeLit: "single", prix: 160 },
      { typeChambre: "quadruple", typeLit: "single", prix: 285 },
    ],
    rating: 3.9,
    BreakfastIncluded: true,
    proximity: 6,
    description: "Auberge charmante avec restaurant local.",
    images: [],
    thumbnail: "",
    tags: ["charming", "local"],
    status: "privé",
  },
  {
    name: "Hôtel des Palmiers",
    type: "hotel",
    slug: "hotel-des-palmiers",
    note: 4.4,
    country: "Maroc",
    city: "Agadir",
    availability: true,
    address: "22 Avenue des Palmiers",
    services: ["wifi", "pool", "gym", "restaurant"],
    prix_basique: 210,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 215 },
      { typeChambre: "double", typeLit: "twin", prix: 210 },
      { typeChambre: "single", typeLit: "single", prix: 205 },
    ],
    rating: 4.4,
    BreakfastIncluded: true,
    proximity: 3,
    description: "Hôtel confortable avec piscine et salle de sport.",
    images: [],
    thumbnail: "",
    tags: ["pool", "fitness"],
    status: "libre",
  },
  {
    name: "Riad Safa",
    type: "riad",
    slug: "riad-safa",
    note: 4.0,
    country: "Maroc",
    city: "Fès",
    availability: true,
    address: "12 Rue Safa",
    services: ["wifi", "laundry", "parking"],
    prix_basique: 180,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 185 },
      { typeChambre: "single", typeLit: "single", prix: 180 },
      { typeChambre: "quadruple", typeLit: "single", prix: 300 },
    ],
    rating: 4.0,
    BreakfastIncluded: false,
    proximity: 4,
    description: "Riad tranquille avec accès facile au centre-ville.",
    images: [],
    thumbnail: "",
    tags: ["quiet", "central"],
    status: "privé",
  },
  {
    name: "Auberge Bleu Ciel",
    type: "auberge",
    slug: "auberge-bleu-ciel",
    note: 3.6,
    country: "Maroc",
    city: "Chefchaouen",
    availability: true,
    address: "15 Rue du Ciel",
    services: ["wifi", "restaurant", "parking"],
    prix_basique: 145,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 150 },
      { typeChambre: "single", typeLit: "single", prix: 145 },
      { typeChambre: "quadruple", typeLit: "single", prix: 270 },
    ],
    rating: 3.6,
    BreakfastIncluded: true,
    proximity: 7,
    description: "Auberge paisible avec vue sur les montagnes.",
    images: [],
    thumbnail: "",
    tags: ["peaceful", "mountain"],
    status: "libre",
  },
  {
    name: "Hôtel Atlantic",
    type: "hotel",
    slug: "hotel-atlantic",
    note: 4.3,
    country: "Maroc",
    city: "Tangier",
    availability: true,
    address: "5 Boulevard Atlantique",
    services: ["wifi", "pool", "gym", "restaurant"],
    prix_basique: 225,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 230 },
      { typeChambre: "double", typeLit: "twin", prix: 225 },
      { typeChambre: "single", typeLit: "single", prix: 220 },
    ],
    rating: 4.3,
    BreakfastIncluded: true,
    proximity: 2,
    description: "Hôtel moderne avec vue sur l'océan.",
    images: [],
    thumbnail: "",
    tags: ["modern", "ocean_view"],
    status: "privé",
  },
  {
    name: "Riad Bahia",
    type: "riad",
    slug: "riad-bahia",
    note: 4.2,
    country: "Maroc",
    city: "Marrakech",
    availability: true,
    address: "9 Rue Bahia",
    services: ["wifi", "laundry", "parking"],
    prix_basique: 180,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 185 },
      { typeChambre: "single", typeLit: "single", prix: 180 },
      { typeChambre: "quadruple", typeLit: "single", prix: 310 },
    ],
    rating: 4.2,
    BreakfastIncluded: false,
    proximity: 3,
    description: "Riad confortable avec patio fleuri.",
    images: [],
    thumbnail: "",
    tags: ["comfort", "patio"],
    status: "libre",
  },
  {
    name: "Auberge des Palmiers",
    type: "auberge",
    slug: "auberge-des-palmiers",
    note: 3.8,
    country: "Maroc",
    city: "Essaouira",
    availability: true,
    address: "7 Route des Palmiers",
    services: ["wifi", "restaurant", "parking"],
    prix_basique: 160,
    rooms: [
      { typeChambre: "double", typeLit: "double", prix: 165 },
      { typeChambre: "single", typeLit: "single", prix: 160 },
      { typeChambre: "quadruple", typeLit: "single", prix: 290 },
    ],
    rating: 3.8,
    BreakfastIncluded: true,
    proximity: 5,
    description: "Auberge agréable proche de la plage.",
    images: [],
    thumbnail: "",
    tags: ["beach", "friendly"],
    status: "privé",
  },
];

export const seedHebergement = async (req, res) => {
  try {
    console.log(seedHebergements.length);
    const seedData = await Hebergement.insertMany(seedHebergements);
    res.status(200).json({ message: 'seeding successful' });
  } catch (error) {
    res.status(500).json({ message: error });
  }
};
